name: PHP Composer

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: "Updating repository /fin"
      run: cd ~/public_html/fin/
           git pull origin main
    - name: "Updating repository /ktd"
      run: cd ~/public_html/ktd2022.abase.id/
           git pull origin main
    - name: "Updating repository /atl"
      run: cd ~/public_html/atl2022.abase.id/
           git pull origin main

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
